/**
 * Generated by `tango codegen relations`.
 * Do not edit this file directly.
 */
declare global {
    interface TangoGeneratedRelationRegistry {
        'blog/Comment': {
            author: { target: (typeof import('../src/models/index.ts'))['UserModel']; cardinality: 'single' };
            post: { target: (typeof import('../src/models/index.ts'))['PostModel']; cardinality: 'single' };
        };
        'blog/Post': {
            author: { target: (typeof import('../src/models/index.ts'))['UserModel']; cardinality: 'single' };
            comments: { target: (typeof import('../src/models/index.ts'))['CommentModel']; cardinality: 'many' };
        };
        'blog/User': {
            comments: { target: (typeof import('../src/models/index.ts'))['CommentModel']; cardinality: 'many' };
            posts: { target: (typeof import('../src/models/index.ts'))['PostModel']; cardinality: 'many' };
        };
    }
}
export type __TangoGeneratedRelationRegistryModule = TangoGeneratedRelationRegistry;
