/**
 * Bundled exports for Django-style domain drill-down imports, plus curated
 * top-level symbols for TS-native ergonomic imports.
 */
export * as domain from './domain/index';
export * as model from './model/index';

export type {
    DeleteReferentialAction,
    Field,
    FieldType,
    IndexDef,
    ModelHookModel,
    ModelKeyOf,
    ModelAugmentations,
    ModelMetadata,
    PersistedModelOutput,
    ModelWriteHookManager,
    ModelWriteHooks,
    BeforeCreateHookArgs,
    AfterCreateHookArgs,
    BeforeUpdateHookArgs,
    AfterUpdateHookArgs,
    BeforeDeleteHookArgs,
    AfterDeleteHookArgs,
    BeforeBulkCreateHookArgs,
    AfterBulkCreateHookArgs,
    RelationDef,
    RelationType,
    UpdateReferentialAction,
} from './domain/index';
export {
    Model,
    RelationBuilder,
    ModelRegistry,
    ImplicitManyToManyIdentifier,
    GENERATED_RELATION_REGISTRY_DIRNAME,
    GENERATED_RELATION_REGISTRY_METADATA_FILENAME,
    GENERATED_RELATION_REGISTRY_METADATA_VERSION,
    GENERATED_RELATION_REGISTRY_TYPES_FILENAME,
    ResolvedRelationGraphArtifactFactory,
    registerModelAugmentor,
    Constraints,
    Decorators,
    Indexes,
    Meta,
    c,
    i,
    m,
    t,
    type ModelDefinition,
    type ForeignKeyDecoratorConfig,
    type FieldDecoratorBuilder,
    type DecoratedFieldKind,
    type ManyToManyDecoratorConfig,
    type ModelRef,
    type ModelRefTarget,
    type GeneratedRelationRegistryArtifact,
    type OneToOneDecoratorConfig,
    type RelationDecoratedSchema,
    type ResolvedRelationGraphSnapshot,
    type ResolvedRelationGraphSnapshotModel,
    type ResolvedRelationGraphSnapshotRelation,
    type TypedModelRef,
} from './model/index';
export { createSchemaModuleAliases, resolveSchemaModuleEntrypoint } from './resolveSchemaModuleEntrypoint';
