import { TemplateBuilder } from '../../../contracts/template/TemplateBuilder';
import type { FrameworkScaffoldContext } from '../../../contracts/template/ScaffoldTemplate';

export class LayoutTemplateBuilder extends TemplateBuilder {
    constructor() {
        super({ name: 'src/app/layout.tsx' });
    }

    protected override resolveTemplate(_context: FrameworkScaffoldContext): string {
        return `import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Tango Todo App',
    description: 'Generated by tango new --framework next',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
`;
    }
}
