import {
    GENERATED_RELATION_REGISTRY_METADATA_VERSION,
    type GeneratedRelationRegistryArtifact,
    type ResolvedRelationGraphSnapshot,
} from '@danceroutine/tango-schema';

export type GenerateRelationRegistryArtifactsInput = {
    snapshot: ResolvedRelationGraphSnapshot;
    fingerprint: string;
    modelTypeAccessors: Readonly<Record<string, string>>;
};

export type GeneratedRelationRegistryArtifacts = {
    declaration: string;
    metadata: GeneratedRelationRegistryArtifact;
};

/**
 * Generate the ambient relation registry declaration and metadata payload from
 * a finalized relation-graph snapshot.
 */
export function generateRelationRegistryArtifacts({
    snapshot,
    fingerprint,
    modelTypeAccessors,
}: GenerateRelationRegistryArtifactsInput): GeneratedRelationRegistryArtifacts {
    for (const model of snapshot.models) {
        for (const relation of model.relations) {
            if (!relation.capabilities.hydratable) {
                continue;
            }
            if (!modelTypeAccessors[relation.targetModelKey]) {
                throw new Error(
                    `Unable to generate relation typing for '${relation.targetModelKey}'. Ensure the models module exports that model directly or through a one-level object export.`
                );
            }
        }
    }

    const declarationLines = [
        '/**',
        ' * Generated by `tango codegen relations`.',
        ' * Do not edit this file directly.',
        ' */',
        'declare global {',
        '    interface TangoGeneratedRelationRegistry {',
        ...snapshot.models.map((model: ResolvedRelationGraphSnapshot['models'][number]) => {
            const hydratableRelations = model.relations.filter((relation) => relation.capabilities.hydratable);
            const relationLines =
                hydratableRelations.length === 0
                    ? ['            [key: string]: never;']
                    : hydratableRelations.map(
                          (relation: ResolvedRelationGraphSnapshot['models'][number]['relations'][number]) =>
                              `            ${JSON.stringify(relation.name)}: { target: ${modelTypeAccessors[relation.targetModelKey]}; cardinality: ${JSON.stringify(relation.cardinality)} };`
                      );

            return [`        ${JSON.stringify(model.key)}: {`, ...relationLines, '        };'].join('\n');
        }),
        '    }',
        '}',
        'export type __TangoGeneratedRelationRegistryModule = TangoGeneratedRelationRegistry;',
        '',
    ];

    return {
        declaration: declarationLines.join('\n'),
        metadata: {
            version: GENERATED_RELATION_REGISTRY_METADATA_VERSION,
            fingerprint,
            snapshot,
        },
    };
}
