/**
 * Generated by `tango codegen relations`.
 * Do not edit this file directly.
 */
declare global {
    interface TangoGeneratedRelationRegistry {
        'nuxt-blog/Comment': {
            author: {
                target: (typeof import('../lib/models.ts'))['UserModel'];
                cardinality: 'single';
                kind: 'belongsTo';
            };
            post: {
                target: (typeof import('../lib/models.ts'))['PostModel'];
                cardinality: 'single';
                kind: 'belongsTo';
            };
        };
        'nuxt-blog/Post': {
            author: {
                target: (typeof import('../lib/models.ts'))['UserModel'];
                cardinality: 'single';
                kind: 'belongsTo';
            };
            comments: {
                target: (typeof import('../lib/models.ts'))['CommentModel'];
                cardinality: 'many';
                kind: 'hasMany';
            };
            tags: { target: (typeof import('../lib/models.ts'))['TagModel']; cardinality: 'many'; kind: 'manyToMany' };
        };
        'nuxt-blog/User': {
            comments: {
                target: (typeof import('../lib/models.ts'))['CommentModel'];
                cardinality: 'many';
                kind: 'hasMany';
            };
            posts: { target: (typeof import('../lib/models.ts'))['PostModel']; cardinality: 'many'; kind: 'hasMany' };
        };
    }
}
export type __TangoGeneratedRelationRegistryModule = TangoGeneratedRelationRegistry;
