export const InternalLookupType = {
    EXACT: 'exact',
    LT: 'lt',
    LTE: 'lte',
    GT: 'gt',
    GTE: 'gte',
    IN: 'in',
    ISNULL: 'isnull',
    CONTAINS: 'contains',
    ICONTAINS: 'icontains',
    STARTSWITH: 'startswith',
    ISTARTSWITH: 'istartswith',
    ENDSWITH: 'endswith',
    IENDSWITH: 'iendswith',
} as const;
