name: Docs

on:
    push:
        branches:
            - main
        paths:
            - 'docs/**'
            - '.github/workflows/docs.yml'
            - '.github/workflows/docs-pages.reusable.yml'
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: docs-pages
    cancel-in-progress: true

jobs:
    pages:
        name: Docs Pages
        uses: danceroutine/tango/.github/workflows/docs-pages.reusable.yml@main
